#!/usr/bin/env bash
# Create isolated benchmark runner virtualenvs so dependencies do not conflict.

set -euo pipefail
if [[ "${TRACE:-0}" == "1" ]]; then
    set -x
fi

usage() {
    cat <<'EOF'
Usage:
  bash scripts/setup_runner_venvs.sh [runner...]

Creates one virtualenv per benchmark runner under:
  ~/scratch/forgetting-llms/.venvs

Supported runners:
  lighteval  evalplus  labbench  safety  bfcl  rg_mix

If no runners are supplied, installs:
  lighteval evalplus labbench

This script also updates:
  ~/scratch/forgetting-llms/benchmark_env.sh

so run_eval.py can activate each runner's env automatically.

Environment knobs:
  SCRATCH_ROOT=~/scratch/forgetting-llms
  VENV_ROOT=~/scratch/forgetting-llms/.venvs
  BENCHMARK_ENV_FILE=~/scratch/forgetting-llms/benchmark_env.sh
  LABBENCH_REPO_ROOT=~/scratch/LAB-Bench
  SAFETY_EVAL_ROOT=~/scratch/safety-eval
  BFCL_ROOT=~/scratch/gorilla/berkeley-function-call-leaderboard
  RG_MIX_ROOT=...   Optional rg_mix_env checkout; auto-detected if present
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

SCRATCH_ROOT="${SCRATCH_ROOT:-$HOME/scratch/forgetting-llms}"
VENV_ROOT="${VENV_ROOT:-$SCRATCH_ROOT/.venvs}"
BENCHMARK_ENV_FILE="${BENCHMARK_ENV_FILE:-$SCRATCH_ROOT/benchmark_env.sh}"
LABBENCH_REPO_ROOT="${LABBENCH_REPO_ROOT:-$HOME/scratch/LAB-Bench}"
SAFETY_EVAL_ROOT="${SAFETY_EVAL_ROOT:-$HOME/scratch/safety-eval}"
BFCL_ROOT="${BFCL_ROOT:-$HOME/scratch/gorilla/berkeley-function-call-leaderboard}"
DEFAULT_RG_MIX_ROOT=""
if [[ -f "$SCRIPT_DIR/../environments/rg_mix_env/rg_mix_env.py" ]]; then
    DEFAULT_RG_MIX_ROOT="$SCRIPT_DIR/../environments/rg_mix_env"
elif [[ -f "$SCRIPT_DIR/../../contextual_learning2/environments/rg_mix_env/rg_mix_env.py" ]]; then
    DEFAULT_RG_MIX_ROOT="$SCRIPT_DIR/../../contextual_learning2/environments/rg_mix_env"
fi
RG_MIX_ROOT="${RG_MIX_ROOT:-$DEFAULT_RG_MIX_ROOT}"

mkdir -p "$SCRATCH_ROOT" "$VENV_ROOT"

module load python/3.10 >/dev/null 2>&1 || true

if [[ $# -gt 0 ]]; then
    RUNNERS=("$@")
else
    RUNNERS=(lighteval evalplus labbench)
fi

upsert_export() {
    local file="$1"
    local var_name="$2"
    local var_value="$3"
    local tmp
    tmp=$(mktemp)
    if [[ -f "$file" ]]; then
        awk -v key="$var_name" -v value="$var_value" '
            BEGIN { done = 0 }
            $0 ~ "^export " key "=" {
                print "export " key "=\"" value "\""
                done = 1
                next
            }
            { print }
            END {
                if (!done) {
                    print "export " key "=\"" value "\""
                }
            }
        ' "$file" > "$tmp"
    else
        {
            print "# Auto-generated by scripts/setup_runner_venvs.sh"
            print "export " var_name "=\"" var_value "\""
        } > "$tmp"
    fi
    mv "$tmp" "$file"
}

create_venv() {
    local name="$1"
    local venv_dir="$VENV_ROOT/$name"
    if [[ ! -x "$venv_dir/bin/python" ]]; then
        python3 -m venv "$venv_dir"
    fi
    # shellcheck disable=SC1090
    source "$venv_dir/bin/activate"
    python3 -m pip install -U pip wheel setuptools
}

install_lighteval() {
    create_venv "lighteval"
    python3 -m pip install -U \
        "lighteval==0.13.0" \
        "vllm==0.10.1" \
        "transformers<5" \
        accelerate \
        sentencepiece \
        nltk \
        more-itertools
    deactivate
    upsert_export "$BENCHMARK_ENV_FILE" \
        "BENCHMARK_RUNNER_SHELL_PREFIX_LIGHTEVAL" \
        "source $VENV_ROOT/lighteval/bin/activate"
    upsert_export "$BENCHMARK_ENV_FILE" \
        "BENCHMARK_RUNNER_SHELL_PREFIX_SUPERGPQA" \
        "source $VENV_ROOT/lighteval/bin/activate"
}

install_evalplus() {
    create_venv "evalplus"
    python3 -m pip install -U \
        "evalplus" \
        openai \
        httpx \
        "transformers<5" \
        accelerate \
        sentencepiece \
        "tree-sitter>=0.23,<0.24" \
        "tree-sitter-python>=0.23,<0.24"
    deactivate
    upsert_export "$BENCHMARK_ENV_FILE" \
        "BENCHMARK_RUNNER_SHELL_PREFIX_EVALPLUS" \
        "source $VENV_ROOT/evalplus/bin/activate"
}

install_labbench() {
    if [[ -f "$LABBENCH_REPO_ROOT/labbench/pyproject.toml" ]]; then
        local install_root="$LABBENCH_REPO_ROOT/labbench"
    elif [[ -f "$LABBENCH_REPO_ROOT/pyproject.toml" ]]; then
        local install_root="$LABBENCH_REPO_ROOT"
    else
        echo "ERROR: LAB-Bench checkout not found under $LABBENCH_REPO_ROOT" >&2
        echo "Run scripts/setup_tasks_md_benchmarks.sh first or set LABBENCH_REPO_ROOT." >&2
        exit 1
    fi
    create_venv "labbench"
    python3 -m pip uninstall -y labbench >/dev/null 2>&1 || true
    python3 -m pip install -U openai
    python3 -m pip install -e "$install_root"
    deactivate
    upsert_export "$BENCHMARK_ENV_FILE" \
        "BENCHMARK_RUNNER_SHELL_PREFIX_LABBENCH" \
        "source $VENV_ROOT/labbench/bin/activate"
}

install_safety() {
    if [[ ! -f "$SAFETY_EVAL_ROOT/evaluation/eval.py" ]]; then
        echo "ERROR: safety-eval checkout not found under $SAFETY_EVAL_ROOT" >&2
        echo "Run scripts/setup_tasks_md_benchmarks.sh first or set SAFETY_EVAL_ROOT." >&2
        exit 1
    fi
    create_venv "safety"
    python3 -m pip install -r "$SAFETY_EVAL_ROOT/requirements.txt"
    python3 -m pip install -e "$SAFETY_EVAL_ROOT"
    deactivate
    upsert_export "$BENCHMARK_ENV_FILE" \
        "BENCHMARK_RUNNER_SHELL_PREFIX_SAFETY_EVAL" \
        "source $VENV_ROOT/safety/bin/activate"
}

install_bfcl() {
    if [[ ! -f "$BFCL_ROOT/pyproject.toml" && ! -f "$BFCL_ROOT/setup.py" ]]; then
        echo "ERROR: BFCL checkout not found under $BFCL_ROOT" >&2
        echo "Run scripts/setup_tasks_md_benchmarks.sh first or set BFCL_ROOT." >&2
        exit 1
    fi
    create_venv "bfcl"
    python3 -m pip install -e "${BFCL_ROOT}[oss_eval_vllm]"
    python3 -m pip install soundfile
    deactivate
    upsert_export "$BENCHMARK_ENV_FILE" \
        "BENCHMARK_RUNNER_SHELL_PREFIX_BFCL" \
        "source $VENV_ROOT/bfcl/bin/activate"
}

install_rg_mix() {
    create_venv "rg_mix"
    python3 -m pip install -U openai verifiers "reasoning-gym>=0.1.10"
    if [[ -n "$RG_MIX_ROOT" && -f "$RG_MIX_ROOT/pyproject.toml" ]]; then
        python3 -m pip install -e "$RG_MIX_ROOT"
    elif [[ -n "$RG_MIX_ROOT" && -f "$RG_MIX_ROOT/rg_mix_env.py" ]]; then
        echo "RG_MIX_ROOT has rg_mix_env.py but no pyproject.toml; using path-based loading only: $RG_MIX_ROOT"
    else
        echo "RG_MIX_ROOT not found or unset; rg_mix will rely on an already-installed rg-mix-env package or explicit --benchmark-root."
    fi
    deactivate
    upsert_export "$BENCHMARK_ENV_FILE" \
        "BENCHMARK_RUNNER_SHELL_PREFIX_RG_MIX" \
        "source $VENV_ROOT/rg_mix/bin/activate"
}

upsert_export "$BENCHMARK_ENV_FILE" "BFCL_ROOT" "$BFCL_ROOT"
upsert_export "$BENCHMARK_ENV_FILE" "SAFETY_EVAL_ROOT" "$SAFETY_EVAL_ROOT"
if [[ -n "$RG_MIX_ROOT" ]]; then
    upsert_export "$BENCHMARK_ENV_FILE" "RG_MIX_ROOT" "$RG_MIX_ROOT"
fi

for runner in "${RUNNERS[@]}"; do
    case "$runner" in
        lighteval) install_lighteval ;;
        evalplus) install_evalplus ;;
        labbench) install_labbench ;;
        safety) install_safety ;;
        bfcl) install_bfcl ;;
        rg_mix) install_rg_mix ;;
        *)
            echo "ERROR: Unknown runner '$runner'" >&2
            usage >&2
            exit 1
            ;;
    esac
done

echo "Created runner virtualenvs under: $VENV_ROOT"
echo "Updated benchmark env file: $BENCHMARK_ENV_FILE"
